<div class="sidebox">
    <h2>Giới thiệu</h2>
    <div class="vmenu">
        <ul>
            <li>
                Hướng dẫn lập trình CSDL với PHP và MySQL
            </li>
            <li>
                Email: <br/> <a href="mailto:ntson@fit.hcmus.edu.vn">ntson@fit.hcmus.edu.vn</a>
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">    
    <h2>Các chức năng</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php">Trang chủ</a>
            </li>
            <li>
                <a href="index.php?action=list">Xem danh sách sinh viên</a>

            </li>            
            <li>
                <a href="index.php?action=add">Thêm sinh viên</a>
            </li>
        </ul>
    </div>
</div>